from ruby:2.4.1
run apt-get update -y
run apt-get install -y build-essential patch ruby-dev zlib1g-dev liblzma-dev
run apt-get install -y nodejs
run gem install rails
run mkdir /scheduler
add . /scheduler
workdir scheduler

